"""coincap

Revision ID: fe98523b5bb7
Revises: 306be391ea18
Create Date: 2024-01-27 16:31:39.400673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe98523b5bb7'
down_revision: Union[str, None] = '306be391ea18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('usdPrice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker', 'usdPrice')
    # ### end Alembic commands ###
